[general]
name = "minilib-math"
version = "0.9.2"
fix_version = "1.5.0"
authors = ["pt9999"]
license = "MIT"

[build]
opt_level = "basic"
files = [
    "lib/math/bigfloat.fix",
    "lib/math/bigint.fix",
    "lib/math/bignat.fix",
    "lib/math/complex.fix",
    "lib/math/euclid.fix",
    "lib/math/modular.fix",
    "lib/math/polynomial.fix",
    "lib/math/rational.fix",
    "lib/math/ring.fix",
    "lib/math/types.fix",
]

[build.test]
opt_level = "basic"
files = [
    "tests/test.fix",
    "tests/math/bigfloat_test.fix",
    "tests/math/bigint_test.fix",
    "tests/math/bignat_test.fix",
    "tests/math/complex_test.fix",
    "tests/math/euclid_test.fix",
    "tests/math/modular_test.fix",
    "tests/math/polynomial_test.fix",
    "tests/math/rational_test.fix",
    "tests/math/ring_test.fix",
]

[[dependencies]]
name = "math"
version = "2.0.0"
git = { url = "https://github.com/tttmmmyyyy/fixlang-math.git" }

[[dependencies]]
name = "random"
version = "1.1.2"
git = { url = "https://github.com/tttmmmyyyy/fixlang-random.git" }

[[dependencies]]
name = "minilib-common"
version = "0.14.0"
# path = "../fixlang-minilib-common"
git = { url = "https://github.com/pt9999/fixlang-minilib-common.git" }

[[dependencies]]
name = "minilib-binary"
version = "0.7.2"
# path = "../fixlang-minilib-binary"
git = { url = "https://github.com/pt9999/fixlang-minilib-binary.git" }

[[dependencies]]
name = "minilib-monad"
version = "0.12.0"
# path = "../fixlang-minilib-monad"
git = { url = "https://github.com/pt9999/fixlang-minilib-monad.git" }

[[dependencies]]
name = "minilib-random"
version = "0.8.1"
git = { url = "https://github.com/pt9999/fixlang-minilib-random.git" }
